version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres  
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/winequality.csv:/data/winequality.csv
      - ../data/data2:/var/lib/postgresql/data
    ports:
      - 5432:5432